### ISSUE TITLE
RDS Credentials are open for public

### ISSUE THREAD

**Issue by sameedshoaibb** [Envue-Team/nefrcservergit#15]
Hey, I have just discovered that your RDS details are open for public, so I want to bring into your knowledge so that you can remove it as soon as possible.
![image](https://user-images.githubusercontent.com/13523236/101254092-7678e080-3740-11eb-8cdb-85f50a1edf6d.png)

**Comment by Envue-Team** [comment]
Repository made private. Config file deleted
